{{ $fullName := include "chart.serviceAccountName" . }}
{{- if .Values.controllerManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spacelift-workerpool-controller
    app.kubernetes.io/part-of: spacelift-workerpool-controller
  {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
{{- end }}
